### ISSUE TITLE
typeof define check

### ISSUE THREAD

**Issue by asapach** [systemjs/babel-plugin-transform-amd-system-wrapper#3]
Rather than visiting all identifiers: https://github.com/systemjs/babel-plugin-transform-amd-system-wrapper/blob/11fa0387135f880d263865d56c546bfebcb7d77b/src/index.js#L423-438
it would be more efficient to visit only UnaryExpression to check for `typeof define`.

**Comment by jrauschenbusch** [comment]
@asapach Please check the referenced commit

**Comment by asapach** [comment]
LGTM
